

export const LOADING_ACTION = 'LOADING';
export const VIEW_ITEMS_ACTION = 'VIEW_ITEMS';
export const INCREASE_QUANTITY_ACTION = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY_ACTION = 'DECREASE_QUANTITY';
export const DELETE_ITEM_ACTION = 'DELETE_ITEM';
export const GET_TOTAL_ACTION = 'GET_TOTAL';
export const CLEAR_CART_ACTION = 'CLEAR_CART';
export const TOGGLE_QUANTITY_ACTION = 'TOGGLE_QUANTITY';
